# Generated by Django 6.0.6 on 2026-07-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Nom court')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_age', models.PositiveSmallIntegerField(verbose_name='Âge minimum')),
                ('max_age', models.PositiveSmallIntegerField(verbose_name='Âge maximum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/categories/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'min_age'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectives', models.TextField(blank=True, verbose_name='Objectifs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/programs/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academy.trainingcategory')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Lundi'), ('TUESDAY', 'Mardi'), ('WEDNESDAY', 'Mercredi'), ('THURSDAY', 'Jeudi'), ('FRIDAY', 'Vendredi'), ('SATURDAY', 'Samedi'), ('SUNDAY', 'Dimanche')], max_length=20, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Lieu')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academy.trainingcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Horaire d'entraînement",
                'verbose_name_plural': "Horaires d'entraînement",
                'ordering': ['category', 'day', 'start_time'],
            },
        ),
    ]
