# Generated by Django 6.0.6 on 2026-07-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('season', models.CharField(blank=True, max_length=20, verbose_name='Saison')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competitions/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compétition',
                'verbose_name_plural': 'Compétitions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=150, verbose_name='Adversaire')),
                ('location', models.CharField(max_length=150, verbose_name='Lieu')),
                ('match_date', models.DateTimeField(verbose_name='Date')),
                ('home_match', models.BooleanField(default=True, verbose_name='Match à domicile')),
                ('our_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score AS Dream Team')),
                ('opponent_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score adverse')),
                ('status', models.CharField(choices=[('UPCOMING', 'À venir'), ('LIVE', 'En cours'), ('FINISHED', 'Terminé'), ('POSTPONED', 'Reporté')], default='UPCOMING', max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Commentaire')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition', verbose_name='Compétition')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['-match_date'],
            },
        ),
    ]
