"""
Django settings for asdreamteam project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import dj_database_url
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


DEBUG = env.bool("DEBUG", default=False)

SECRET_KEY = env("SECRET_KEY")


ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://asdreamteam.club",
    "https://www.asdreamteam.club",
    "https://authentic-blessing-production-ca37.up.railway.app",
    "https://asdreamteam.up.railway.app",
    "https://asdreamnteam-production.up.railway.app",
    "https://asdreamteam.co",
    "https://www.asdreamteam.co",
]


# --------------------------------------------------
# Applications
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize',
    
    'storages',

    'pages',
    'team',
    'academy',
    'competitions',
    'news',
    'gallery',
    'contact',
    'membership',
    'donation',

    'crispy_forms',
    'crispy_bootstrap5',
    'fontawesomefree',
]

# --------------------------------------------------
# Middleware
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------
# Templates
# --------------------------------------------------
ROOT_URLCONF = "asdreamteam.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            'asdreamteam/templates',
            'pages/templates',
            'contact/templates',
            'team/templates',
            'academy/templates',
            'competitions/templates',
            'gallery/templates',
            'news/templates',
            #'join/templates',
            'donation/templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "asdreamteam.context_processors.menu_items_context",
                "asdreamteam.context_processors.site_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "asdreamteam.wsgi.application"

# --------------------------------------------------
# Database (local par défaut)
# --------------------------------------------------
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}

# os.environ.setdefault("PGDATABASE", "liftoff_dev")
# os.environ.setdefault("PGUSER", "username")
# os.environ.setdefault("PGPASSWORD", "")
# os.environ.setdefault("PGHOST", "localhost")
# os.environ.setdefault("PGPORT", "5432")

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ["PGDATABASE"],
#         'USER': os.environ["PGUSER"],
#         'PASSWORD': os.environ["PGPASSWORD"],
#         'HOST': os.environ["PGHOST"],
#         'PORT': os.environ["PGPORT"],
#     }
# }

# --------------------------------------------------
# Password validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# Static & Media
# --------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "asdreamteam/static"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


#------------------------------------------------------#
#           AWS S3 Storagefor Media                    #
#------------------------------------------------------#

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")

AWS_S3_REGION_NAME = env(
    "AWS_S3_REGION_NAME",
    default="eu-west-3",
)
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_ADDRESSING_STYLE = "virtual"

# DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "file_overwrite": False,
            "default_acl": None,
            "querystring_auth": False,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = (
    f"https://{AWS_STORAGE_BUCKET_NAME}.s3."
    f"{AWS_S3_REGION_NAME}.amazonaws.com/"
)

# MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"


# --------------------------------------------------
# Email
# --------------------------------------------------
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = env("ADMIN_EMAIL", default=EMAIL_HOST_USER)

# EMAIL_HOST_USER = env("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# --------------------------------------------------
# CONSTANTS SITE INFO
# --------------------------------------------------

SITE_NAME = "AS Dream Team"
SITE_TAGLINE = "Football • Formation • Ambition"
DEVELOPER_NAME = "KMK-IoTech"
DEVELOPER_URL = "https://kmk-iotech.com"


PAYPAL_HOSTED_BUTTON_ID = env(
    "PAYPAL_HOSTED_BUTTON_ID",
    default="",
).strip()

ORANGE_MONEY_PAYMENT_URL = env(
    "ORANGE_MONEY_PAYMENT_URL",
    default="https://www.tresor.ongdreamteam.com/orangemoneypayment",
).strip()


# --------------------------------------------------
# Other
# --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"